### ISSUE TITLE
dialogflow proxy does not display Actions On Google messages

### ISSUE THREAD

**Issue by AsistenteV1rtu4lComfacauca** [Tiledesk/dialogflowproxy#1]
Hello friend, implement the proxy for dialogflow but it only shows default messages and not the messages implemented in Actions on Google, there is some way to enable the call to messages of Actions on Google

Sorry my bad english

**Comment by sponzillo** [comment]
Hi,

do you have a public page where I can see the widget?

**Comment by AsistenteV1rtu4lComfacauca** [comment]
Hi friend, not yet, I am doing tests in a development environment before publishing the project.

I appreciate your timely response

**Comment by AsistenteV1rtu4lComfacauca** [comment]
> Hi,
> 
> do you have a public page where I can see the widget?

Hello friend, not yet, I am doing tests in a development environment before publishing the project.

I appreciate your timely response

**Comment by Jone8293** [comment]
Hi 


We are getting a few problems:

1 We have set our welcome intent to understand __start however it is not registering and keeps asking can you say that again? how did you get your bot to start with your intro?

2.Also, we've noticed that even though our bot is English the minutes and comments are still in Italian,
3. We just tried to install this application on a cloudways server with node and we get this error when we try to NPM start

SyntaxError: Unexpected token function                                                                                                                                
    at createScript (vm.js:56:10)                                                                                                                                     
    at Object.runInThisContext (vm.js:97:10)                                                                                                                          
    at Module._compile (module.js:549:28)                                                                                                                             
    at Object.Module._extensions..js (module.js:586:10)                                                                                                               
    at Module.load (module.js:494:32)                                                                                                                                 
    at tryModuleLoad (module.js:453:12)                                                                                                                               
    at Function.Module._load (module.js:445:3)                                                                                                                        
    at Module.runMain (module.js:611:10)                                                                                                                              
    at run (bootstrap_node.js:394:7)                                                                                                                                  
    at startup (bootstrap_node.js:160:9)                                                                                                                              
                                                                                                                                                                      
npm ERR! Linux 4.9.0-11-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tiledesk-node-jwt@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiledesk-node-jwt@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tiledesk-node-jwt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tiledesk-node-jwt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tiledesk-node-jwt
npm ERR! There is likely additional logging output above.


Any help please

**Comment by sponzillo** [comment]
As soon as you have a public page to test your widget let me know. Eventually send me the page address privately so I can take a look.

**Comment by hjgabrielsen** [comment]
Any progress on displaying "Actions on Google" messages? (Tab 2 in Dialogflow 😉) - this would be awesome

**Comment by sponzillo** [comment]
Hi Gabriel,

This project is deprecated, you can now use directly Tiledesk and his Native Dialogflow Connector to achieve your task.

Andrea

**Comment by sponzillo** [comment]
> Any progress on displaying "Actions on Google" messages? (Tab 2 in Dialogflow 😉) - this would be awesome

Hi Gabriel,

This project is deprecated, you can now use directly Tiledesk and his Native Dialogflow Connector to achieve your task.

Andrea
