### ISSUE TITLE
Dialogflow Proxy  few issues

### ISSUE THREAD

**Issue by Jone8293** [Tiledesk/dialogflowproxy#5]
Hi

We are getting a few problems:

1 We have set our welcome intent to understand __start however it is not registering and keeps asking can you say that again? how did you get your bot to start with your intro?

2.Also, we've noticed that even though our bot is English the minutes and comments are still in Italian,
3. We just tried to install this application on a cloudways server with node and we get this error when we try to NPM start

SyntaxError: Unexpected token function
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.runMain (module.js:611:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:160:9)

npm ERR! Linux 4.9.0-11-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tiledesk-node-jwt@1.0.0 start: node index.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiledesk-node-jwt@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tiledesk-node-jwt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs tiledesk-node-jwt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls tiledesk-node-jwt
npm ERR! There is likely additional logging output above.

Any help please

**Comment by sponzillo** [comment]
About point 1 (the other points later). Did you train correctly a Dialogflow intent to reply correctly to the __start (or whatever else) message? You need a intent with the correct training phrase (see image)

![image](https://user-images.githubusercontent.com/32564846/70615330-7963f280-1c0c-11ea-93aa-7f6a3f591dcd.png)

**Comment by atsoares** [comment]
How to change the "4 minuti fa" in the time tag?
